# Compiler
CC=gcc

# Target name
TARGET = writer

# Source files
SRC = writer.c

# Compile the program
all:
	$(CROSS_COMPILE)$(CC) -o $(TARGET) $(SRC)

default:
	$(CROSS_COMPILE)$(CC) -o $(TARGET) $(SRC)

clean :
	rm $(TARGET)